language: php
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
after_script:
  - vendor/bin/test-reporter
php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
addons:
  code_climate:
    repo_token: 3946e245abf72c287dd79cf8f2e3c50fda8d8234f9531ca09ee7c6711954ed92