language: php
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4